// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeBuB3BfqMLvltOZ9HDBpWCeeuY4ifi5g',
    appId: '1:235935344137:web:de64b6ab760e50a16dbad8',
    messagingSenderId: '235935344137',
    projectId: 'e-commerce-28ad9',
    authDomain: 'e-commerce-28ad9.firebaseapp.com',
    storageBucket: 'e-commerce-28ad9.firebasestorage.app',
    measurementId: 'G-1D3EFQ1N1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvu-xtBg5CWsJbmhA2Q7ueMXyJCOzE-s',
    appId: '1:235935344137:android:be79fdb6d493f8bd6dbad8',
    messagingSenderId: '235935344137',
    projectId: 'e-commerce-28ad9',
    storageBucket: 'e-commerce-28ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBGdzLcprOcUWEUI3AGx7bEO9C4HnWjX8',
    appId: '1:235935344137:ios:49b9cbb126729f7c6dbad8',
    messagingSenderId: '235935344137',
    projectId: 'e-commerce-28ad9',
    storageBucket: 'e-commerce-28ad9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppWithDjango',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBGdzLcprOcUWEUI3AGx7bEO9C4HnWjX8',
    appId: '1:235935344137:ios:49b9cbb126729f7c6dbad8',
    messagingSenderId: '235935344137',
    projectId: 'e-commerce-28ad9',
    storageBucket: 'e-commerce-28ad9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppWithDjango',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeBuB3BfqMLvltOZ9HDBpWCeeuY4ifi5g',
    appId: '1:235935344137:web:9eefbb7f3db0aa756dbad8',
    messagingSenderId: '235935344137',
    projectId: 'e-commerce-28ad9',
    authDomain: 'e-commerce-28ad9.firebaseapp.com',
    storageBucket: 'e-commerce-28ad9.firebasestorage.app',
    measurementId: 'G-3PK3ZX6QE5',
  );
}
